# LDA

In [ ]:
import pandas as pd
import numpy as np

npr = pd.read_csv('npr.csv')

In [ ]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [ ]:
npr["Article"][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [ ]:
len(npr)

11992

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [ ]:
dtm = cv.fit_transform(npr['Article'])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=7, random_state=42)

In [ ]:
lda.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [ ]:
# Grab the vocabulary of words

In [ ]:
len(cv.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


54777

In [ ]:
import random
cv.get_feature_names()[random.randint(0,54777)]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'diwali'

In [ ]:
# Grab the topics

In [ ]:
len(lda.components_)

7

In [ ]:
lda.components_.shape

(7, 54777)

In [ ]:
single_topic = lda.components_[0]

In [ ]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [ ]:
single_topic.argsort()[-10:] # Grab 10 highest value index positions

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [ ]:
top_ten_words = single_topic.argsort()[-20:]
for index in top_ten_words:
  print(cv.get_feature_names()[index])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [ ]:
# Grab the highest probability words per topic

In [ ]:
for i,topic in enumerate(lda.components_):
  print(f"Top 15 words for Topic #{i}")
  print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
  print("\n")

Top 15 words for Topic #0


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


Top 15 words for Topic #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


Top 15 words for Topic #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


Top 15 words for Topic #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


Top 15 words for Topic #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


Top 15 words for Topic #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']


Top 15 words for Topi

In [ ]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [ ]:
topic_results = lda.transform(dtm)

In [ ]:
topic_results.shape

(11992, 7)

In [ ]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [ ]:
topic_results[0].argmax()

1

In [ ]:
npr['Topic'] = topic_results.argmax(axis=1)
npr.head(20)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      1
4   From photography, illustration and video, to d...      2
5   I did not want to join yoga class. I hated tho...      3
6   With a   who has publicly supported the debunk...      3
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      3
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      2
14  Being overweight can raise your blood pressure...      3
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      2
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1

# NMF

In [ ]:
import pandas as pd
npr = pd.read_csv('npr.csv')

In [ ]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [ ]:
dtm = tfidf.fit_transform(npr["Article"])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.decomposition import NMF
nmf_model = NMF(n_components=7,random_state=42)
nmf_model.fit(dtm)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


NMF(n_components=7, random_state=42)

In [ ]:
tfidf.get_feature_names()[2301]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'albania'

In [ ]:
for i,topic in enumerate(nmf_model.components_):
  print(f"The top 15 words for Topic #{i}")
  print([tfidf.get_feature_names()[index] for index in topic.argsort()[-15:]])
  print("\n")

The top 15 words for Topic #0


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


The top 15 words for Topic #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


The top 15 words for Topic #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


The top 15 words for Topic #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


The top 15 words for Topic #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


The top 15 words for Topic #5
['love', 've', 'don', 'album', 'way', 'time', 'song', '

In [ ]:
topic_results = nmf_model.transform(dtm)

In [ ]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3])

In [ ]:
npr['Topic'] = topic_results.argmax(axis=1)

In [ ]:
npr.head(20)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      3
4   From photography, illustration and video, to d...      6
5   I did not want to join yoga class. I hated tho...      5
6   With a   who has publicly supported the debunk...      0
7   I was standing by the airport exit, debating w...      0
8   If movies were trying to be more realistic, pe...      0
9   Eighteen years ago, on New Year’s Eve, David F...      5
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      0
13  For the last installment of NPR’s holiday reci...      5
14  Being overweight can raise your blood pressure...      0
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      3
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1

In [ ]:
topic_dict = {0:"health",1:"campaigning",2:"legislation",3:"politics",4:"election",5:"music",6:"edu"}
npr["Topic Label"] = npr["Topic"].map(topic_dict)
npr.head(20)

Article  Topic  Topic Label
0   In the Washington of 2016, even when the polic...      1  campaigning
1     Donald Trump has used Twitter  —   his prefe...      1  campaigning
2     Donald Trump is unabashedly praising Russian...      1  campaigning
3   Updated at 2:50 p. m. ET, Russian President Vl...      3     politics
4   From photography, illustration and video, to d...      6          edu
5   I did not want to join yoga class. I hated tho...      5        music
6   With a   who has publicly supported the debunk...      0       health
7   I was standing by the airport exit, debating w...      0       health
8   If movies were trying to be more realistic, pe...      0       health
9   Eighteen years ago, on New Year’s Eve, David F...      5        music
10  For years now, some of the best, wildest, most...      5        music
11  For years now, some of the best, wildest, most...      5        music
12  The Colorado River is like a giant bank accoun...      0       health
13  For the last installment of NPR’s holiday reci...      5        music
14  Being overweight can raise your blood pressure...      0       health
15  Who’s the YouTube star of 2016? Adele singing ...      5        music
16  Here’s a quick roundup of some of the   you ma...      3     politics
17  Ben Johnston doesn’t follow the rules of music...      5        music
18  David Bowie, Prince and George Michael are all...      5        music
19  In November, the typically straitlaced Office ...      1  campaigning